export const RESERVATION_TYPE_TIMETABLE = 'TIMETABLE';
export const RESERVATION_TYPE_ACTIVITY = 'ACTIVITY';

export const RESERVATION_STATUS_PENDING = 'PENDING';
export const RESERVATION_STATUS_CONFIRM = 'CONFIRM';
export const RESERVATION_STATUS_AFTER_HOUR = 'AFTER_HOUR';

export const RESERVATION_COLOR_TIMETABLE = '#000080';
export const RESERVATION_COLOR_PENDING = '#FF6699';
export const RESERVATION_COLOR_CONFIRM = '#663300';
export const RESERVATION_COLOR_AFTER_HOUR = '#FF6699';

export const START_TIME_AFTER_HOUR = '17:00:01';
export const END_TIME_AFTER_HOUR = '21:00:00';

export const TIMETABLE_ID = 0;
export const RESERVATION_STATUS = 'RESERVATION';

